# Generated by Django 2.2.5 on 2022-07-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ohio',
        ),
    ]
